#!/usr/bin/python3
import socket
import sys

from alan_composer.app import Composer, SOCKET


if len(sys.argv) == 2 and sys.argv[1] in {"open", "recover"}:
    with socket.socket(socket.AF_UNIX) as client:
        client.connect(str(SOCKET))
        client.sendall(sys.argv[1].upper().encode() + b"\n")
else:
    Composer().start()
